### PR TITLE
fix: use release-api for gitlab

### PR DESCRIPTION
**Pull request by FirstSanny**
Used the release api from python-gitlab instead of the outdated tag api.

Solves this [issue](https://github.com/relekang/python-semantic-release/issues/350)

### CODE REVIEW

**Comment by relekang** [comment]
Nice, can you please fix the broken tests?

**Comment by FirstSanny** [comment]
> 
> 
> Nice, can you please fix the broken tests?

fixed them. but since the test is only running against mocks i am not sure how safe these tests are. 😄

**Comment by relekang** [comment]
Hehe, valid point 😅 
The mocks for these integrations should probably be at the http layer.

**Comment by FirstSanny** [comment]
> 
> 
> Hehe, valid point 😅
> The mocks for these integrations should probably be at the http layer.

But i guess this would be a new issue 😉 

Do need to provide anything else?

**Comment by relekang** [comment]
Of course, did not mean that it should be done here. I forgot to check back after running the github action.

Thanks for fixing this 🙌

**Comment by FirstSanny** [comment]
> 
> 
> Of course, did not mean that it should be done here. I forgot to check back after running the github action.
> 
> Thanks for fixing this 🙌

No problem. 😄

**Pull request merged**
