### PR TITLE
Add --retry cli option

### PR DESCRIPTION
**Pull request by skorokithakis**
Many times, `semantic-release` will die with an error (because of missing tags, files existing on PyPI because I forgot to delete the `dist/` dir, etc etc), leaving me with a half-made commit that I basically have to resume by hand.

This PR makes `semantic-release` idempotent by adding a `--retry` option that will retry the same commit, and will not change the repository. It will also skip existing files on PyPI so the release will be much more likely to succeed.

### CODE REVIEW

**Comment by relekang** [comment]
Master has been updated with CI integration, do you mind rebasing on master so CI will build?

**Comment by skorokithakis** [comment]
Not at all, I'll do that in a few minutes, thank you.

**Comment by relekang** [comment]
Also please add the --retry option to the documentation.

**Comment by skorokithakis** [comment]
This should be done!

**Comment by relekang** [comment]
Thanks :v:

**Comment by relekang** [comment]
It seems python2 broke after one of the recent pull-requests I hope to have a look at it soon and then do a release.

**Comment by relekang** [comment]
This have been released in v3.11.0

**Comment by skorokithakis** [comment]
Fantastic, thank you!

**Pull request merged**
