### PR TITLE
Add configparser to requirements.txt

### PR DESCRIPTION
**Pull request by haeric**
Wouldn't run without :)

### CODE REVIEW

**Comment by relekang** [comment]
Is this with python 2?

**Comment by haeric** [comment]
Indeed it is... 2.7.9 :)

**Comment by relekang** [comment]
Python 2 is not supported :)

Do you know which version and wheel it installed?

**Comment by haeric** [comment]
Awww ;) Maybe state in the docs?
```
~$ pip install python-semantic-release
Collecting python-semantic-release
  Downloading python_semantic_release-0.5.2-py2-none-any.whl
Collecting invoke==0.10.1 (from python-semantic-release)
  Downloading invoke-0.10.1-py2.py3-none-any.whl (166kB)
    100% |████████████████████████████████| 167kB 1.7MB/s 
Collecting click==4.1 (from python-semantic-release)
  Downloading click-4.1-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 65kB 2.8MB/s 
Collecting semver==2.2.0 (from python-semantic-release)
  Downloading semver-2.2.0.tar.gz
Collecting GitPython==1.0.1 (from python-semantic-release)
  Downloading GitPython-1.0.1.tar.gz (355kB)
    100% |████████████████████████████████| 356kB 1.2MB/s 
Collecting gitdb>=0.6.4 (from GitPython==1.0.1->python-semantic-release)
  Downloading gitdb-0.6.4.tar.gz (400kB)
    100% |████████████████████████████████| 401kB 1.2MB/s 
Collecting smmap>=0.8.5 (from gitdb>=0.6.4->GitPython==1.0.1->python-semantic-release)
  Downloading smmap-0.9.0.tar.gz
Installing collected packages: invoke, click, semver, smmap, gitdb, GitPython, python-semantic-release
  Running setup.py install for semver
  Running setup.py install for smmap
  Running setup.py install for gitdb
  Running setup.py install for GitPython
Successfully installed GitPython-1.0.1 click-4.1 gitdb-0.6.4 invoke-0.10.1 python-semantic-release-0.5.2 semver-2.2.0 smmap-0.9.0
```

**Comment by relekang** [comment]
> Maybe state in the docs?

Probably a good idea :smile:

**Comment by relekang** [comment]
Closing this as python 2 support requires a bit more :)

**Pull request closed without merging**
