### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by salimfadhley**

### CODE REVIEW

**Comment by relekang** [comment]
Thanks :)

**Comment by salimfadhley** [comment]
Hey - did you see my email that I sent from work about the problem with PSR
where your python project root is not the same directory as the git project
root?

This is often the case in larger / multilanguage projects.

**Comment by relekang** [comment]
Yes, I'll get to it today :)

**Comment by salimfadhley** [comment]
Thanks, let me know as soon as it hits pypi and I can test it. Unfortunately it's very hard for me to verify the behavior of non-released stuff behind the corporate firewalls.

**Comment by relekang** [comment]
Sorry about that, it should be up now. I had changed my pypi credentials and did not realise i had not updated the config for this project.

**Pull request merged**
